### ISSUE TITLE
0.30.0 release roadmap

### ISSUE THREAD

**Issue by elinorbgr** [Smithay/wayland-rs#431]
Things to do and iterate on with alphas before the actual release

- [x] prototype upgrade of SCTK -- https://github.com/Smithay/client-toolkit/pull/215
- [x] prototype upgrade of Smithay -- https://github.com/Smithay/smithay/pull/454
- [x] Full pass on documentation (including readmes)
  - [x] wayland-sys
  - [x] wayland-backend
  - [x] wayland-scanner
  - [x] wayland-client
  - [x] wayland-server
  - [x] wayland-egl
  - [x] wayland-cursor
  - [x] wayland-protocols
  - [x] main readme of the repo
- [x] deny `unsafe_op_in_unsafe_fn`
- [x] split `wayland-protocols` into multiple crates
- [x] https://github.com/Smithay/wayland-rs/issues/448
- [x] server: don't require a `DataInit` initialization if the created object is already destroyed on callback return (for example if a protocol error was triggered) -- https://github.com/Smithay/wayland-rs/pull/458
- [x] Remove generic argument from `ClientData` or provide state in its callbacks
- [x] https://github.com/Smithay/wayland-rs/pull/497
- [ ] Find a way to improve `wayland-client`'s `event_created_child!()`
- [x] Implement `with_all_objects_for` on the server/sys backend
- [x] Investigate if `DelegateDispatch` can be fused with `Dispatch` : https://github.com/Smithay/wayland-rs/pull/518
- [x] Fix all remaining TODOs

And non-blocking, but overall useful thing to do: improve code coverage by writing more tests, see https://app.codecov.io/gh/Smithay/wayland-rs

**Comment by i509VCB** [comment]
We should probably set deny for the `unsafe_op_in_unsafe_fn` lint.

Fyi this is going to become default or already is in 2021 edition.

**Comment by i509VCB** [comment]
Pending a new release of `nix` to fix the sigpipe signal issue since the new constants are not in nix yet: https://github.com/Smithay/wayland-rs/issues/457

I think we could use libc though for now to temporarily fix that problem>

**Comment by vberger** [comment]
It seems like a `nix` release might not be too far away? https://github.com/nix-rust/nix/milestone/9

**Comment by i509VCB** [comment]
> split wayland-protocols into multiple crates

This has been done

**Comment by A6GibKm** [comment]
> backend::sys::client::Backend::from_foreign_display()

Once this is in, how does one get the WlDisplay?. Or alternatively, if I start with a ptr to a wl_surface how do I make use of this api and get a WlSurface.

**Comment by l4l** [comment]
Is there any migration guide for 0.29.* to the current version?

**Comment by elinorbgr** [comment]
There is no proper guide (yet), but you can refer to [this comment](https://github.com/Smithay/wayland-rs/issues/625#issuecomment-1556753435) for an overview of what changed
